-- Create a table for projects/widgets configuration
create table if not exists projects (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  public_key text unique not null,
  allowed_origins text[] default '{}',
  gemini_api_key text,
  user_id uuid references auth.users(id)
);


-- Index for fast lookups by API key
create index if not exists projects_public_key_idx on projects(public_key);

-- Create a table for simple rate limiting (logging requests)
-- In a high-scale production, use Redis/Upstash instead of a SQL table.
create table if not exists request_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  ip_address text,
  public_key text
);

create index if not exists request_logs_ip_idx on request_logs(ip_address);
create index if not exists request_logs_key_idx on request_logs(public_key);
create index if not exists request_logs_created_at_idx on request_logs(created_at);

-- 3. Row Level Security (RLS) Setup

-- Enable RLS on tables
alter table projects enable row level security;
alter table request_logs enable row level security;

-- Policies for 'projects'
-- Users can only see/edit their own projects
create policy "Users can manage their own projects"
  on projects
  for all
  using (auth.uid() = user_id);

-- Policies for 'request_logs'
-- Users can view logs for their own projects (associated by public_key)
create policy "Users can view logs for their projects"
  on request_logs
  for select
  using (
    public_key in (
      select public_key from projects where user_id = auth.uid()
    )
  );

-- Backend (Service Role) has full access by default to all tables.
-- No explicit policy needed for service_role if using supabaseAdmin (which bypasses RLS).
